Console.Writeline ("[Intro]");
Console.Writeline ("Ayy-ayy, Getzh, you always cooking on");
Console.Writeline ("Uh-uh, yeah-eah, veneno, veneno, veneno");
Console.Writeline ("Uh-uh, yeah-eah, veneno, veneno");
Console.Writeline ("Ya, ya, ya, ya, ya");

Console.Writeline ("[Refrão]");
Console.Writeline ("Tô gotejando, drip veneno" foreground color = ConsoleColor.yellow);
Console.Writeline ("Os mano que inveja, morrendo de raiva" foreground color = ConsoleColor.yellow);
Console.Writeline ("Ice de naja, pinga da presa" foreground color = ConsoleColor.yellow);
Console.Writeline ("Bate cabeça que é chuva de naipe" foreground color = ConsoleColor.yellow);
Console.Writeline ("Tô gotejando, drip veneno" foreground color = ConsoleColor.yellow);
Console.Writeline ("Os mano que inveja, morrendo de raiva" foreground color = ConsoleColor.yellow);
Console.Writeline ("Ice de naja, pinga da presa" foreground color = ConsoleColor.yellow);
Console.Writeline ("Bate cabeça que é chuva de naipe" foreground color = ConsoleColor.yellow);

Console.Writeline ("[Verso 1]");
Console.Writeline ("Mina me olha, efeito reflexo");
Console.Writeline ("Ela se molha, que nem meu Airmax");
Console.Writeline ("Cuida com o cash, saio na chuva");
Console.Writeline ("Pra disfarçar o wet da blusa");
Console.Writeline ("É gringa, cuidado onde pisa");
Console.Writeline ("Vai ter umas poças na volta que o swag pinga");
Console.Writeline ("Sweat né fia, nem se assemelha");
Console.Writeline ("Tô que nem buraco em teto de telha");
Console.Writeline ("Eu digo "Para, para que tá péssimo"");
Console.Writeline ("Show, chama meus amigo que aqui é só acréscimo");
Console.Writeline ("Bota nóis no beat que a sala toda aquece");
Console.Writeline ("The floor is lava, mas aqui não é nordeste");
Console.Writeline ("Os boyzin' do sul");
Console.Writeline ("Soca, desce a porrada efeito Blazblue");
Console.Writeline ("Dropa eles no chão tipo bass boom");
Console.Writeline ("Better run soon, que os maluco tá chegando, pingando, e se tu para we're gon' get you, bitch");
Console.Writeline ("[Refrão]");
Console.Writeline ("Tô gotejando, drip veneno");
Console.Writeline ("Os mano que inveja, morrendo de raiva");
Console.Writeline ("Ice de naja, pinga da presa");
Console.Writeline ("Bate cabeça que é chuva de naipe");
Console.Writeline ("Tô gotejando, drip veneno");
Console.Writeline ("Os mano que inveja, morrendo de raiva");
Console.Writeline ("Ice de naja, pinga da presa");
Console.Writeline ("Bate cabeça que é chuva de naipe");

Console.Writeline ("[Verso 2]");
Console.Writeline ("Teu molhado já tá seco, tá manjado teu style e teu cordão");
Console.Writeline ("Tá usando o que te mandam, o que esperam, o que tu quer, irmão?");
Console.Writeline ("'Cê tem grana, tem de marca, mas não tem customizada");
Console.Writeline ("Minhas blusa tudo eu que fiz, então me diz, quem é o mais foda aqui? Bitch");
Console.Writeline ("Se afasta, tá de Prada, mas é fake, vale nada");
Console.Writeline ("Empire State, elevado, hype brabo, suba a escada");
Console.Writeline ("Tô no topo, 'cê já sabe, Element onde caiba");
Console.Writeline ("Quem não tem, só lamento, só não seja, fake hype");
Console.Writeline ("Se afasta, tá de Prada, mas é fake, vale nada");
Console.Writeline ("Empire State, elevado, hype brabo, suba a escada");
Console.Writeline ("Tô no topo, 'cê já sabe, Element onde caiba");
Console.Writeline ("Quem não tem, só lamento, só não seja, fake hype");
Console.Writeline ("Pode vim pobre ou pode vim rico");
Console.Writeline ("Pode vim tudo que tá tudo bem, oh");
Console.Writeline ("Só não pode vim vocês");
Console.Writeline ("Filha d'uma puta, chama os outros de lame, oh");
Console.Writeline ("Pode vim pobre ou pode vim rico");
Console.Writeline ("Pode vim tudo que tá tudo bem, oh");
Console.Writeline ("Só não pode vim vocês");
Console.Writeline ("Filha d'uma puta, chama os outros de lame, oh filha da puta");

Console.Writeline ("[Refrão]");
Console.Writeline ("Tô gotejando, drip veneno" foreground color = ConsoleColor.yellow);
Console.Writeline ("Os mano que inveja, morrendo de raiva" foreground color = ConsoleColor.yellow);
Console.Writeline ("Ice de naja, pinga da presa" foreground color = ConsoleColor.yellow);
Console.Writeline ("Bate cabeça que é chuva de naipe" foreground color = ConsoleColor.yellow);
Console.Writeline ("Tô gotejando, drip veneno" foreground color = ConsoleColor.yellow);
Console.Writeline ("Os mano que inveja, morrendo de raiva" foreground color = ConsoleColor.yellow);
Console.Writeline ("Ice de naja, pinga da presa" foreground color = ConsoleColor.yellow);
Console.Writeline ("Bate cabeça que é chuva de naipe" foreground color = ConsoleColor.yellow);